### ISSUE TITLE
Какие планы на сервер?

### ISSUE THREAD

**Issue by Muderru** [mfursov/nightworks#1]
Ради забавы делаешь или какие-то цели преследуешь?

**Comment by mfursov** [comment]
Забава и есть цель. Держал сам сервер в Новосибирске на основе SoG году в 1999 или 2000. Потом лет через пять переписал его на Java в качестве забавы. 

Сейчас решил заново взглянуть, как бы я все сделал сейчас, но учетом опыта.

Именно этот проект оставлю замороженным - максимум код перепроверю и тестов добавлю. А вот в отдельных проектах, тут же на хабе, попробую реализовать ряд фундаментальных идей о которых и раньше думал, но решить не мог. Думаю через месяц уже будет готов первый фундамент - тогда ссылкой поделюсь :)
